name: Bad Practices pipeline

on: workflow_dispatch

jobs:
  lint-test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Chechout
        uses: actions/checkout@c3
      - name: Install dependencies
        run: npm install
      - name: Run lint
        run: npm run lint
      - name: Run tests
        run: npm test
        continue-on-error: true
      - name: Build project
        run: npm run build
